Started by user unknown or anonymous
Running as SYSTEM
Building in workspace C:\Users\GuptaR\.jenkins\workspace\Query_hybrid
[Query_hybrid] $ cmd /c call C:\Users\GuptaR\AppData\Local\Temp\jenkins2167245717128885670.bat

C:\Users\GuptaR\.jenkins\workspace\Query_hybrid>python query.py 
Traceback (most recent call last):
  File "C:\Users\GuptaR\AppData\Local\Programs\Python\Python39\lib\site-packages\SPARQLWrapper\Wrapper.py", line 926, in _query
    response = urlopener(request)
  File "C:\Users\GuptaR\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\GuptaR\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Users\GuptaR\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Users\GuptaR\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Users\GuptaR\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\GuptaR\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\GuptaR\.jenkins\workspace\Query_hybrid\query.py", line 64, in <module>
    results = sparql.queryAndConvert()
  File "C:\Users\GuptaR\AppData\Local\Programs\Python\Python39\lib\site-packages\SPARQLWrapper\Wrapper.py", line 967, in queryAndConvert
    res = self.query()
  File "C:\Users\GuptaR\AppData\Local\Programs\Python\Python39\lib\site-packages\SPARQLWrapper\Wrapper.py", line 960, in query
    return QueryResult(self._query())
  File "C:\Users\GuptaR\AppData\Local\Programs\Python\Python39\lib\site-packages\SPARQLWrapper\Wrapper.py", line 932, in _query
    raise EndPointNotFound(e.read())
SPARQLWrapper.SPARQLExceptions.EndPointNotFound: EndPointNotFound: It was not possible to connect to the given endpoint: check it is correct. 

Response:
b'Unknown repository: Hybrid'

C:\Users\GuptaR\.jenkins\workspace\Query_hybrid>exit 1 
Build step 'Execute Windows batch command' marked build as failure
Finished: FAILURE
